swagger: "2.0"
info:
  description: "url ----> pdf,png,jpg,coverage,word,markdown"
  version: "1.0.0"
  title: "URL2WHAT"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/api/v1"
schemes:
- "http"
paths:
